name: Checkout and setup environment
description: Git checkout if not already checked out, get node_modules from cache if available, set up Node.js, run yarn install

inputs:
  is-high-risk-environment:
    description: 'Use a secure setup without caching (true = secure, false = optimized for speed).'
    required: true
  fetch-depth:
    description: 'Depth of the Git history to fetch.'
    required: false
    default: '1'
  ref:
    description: 'Branch, tag, or SHA to checkout.'
    required: false
    default: ''
  cache-node-modules:
    description: 'Enable caching for `node_modules`. Should only be enabled for the `prepare` job, and only applies when is-high-risk-environment is `false`.'
    required: false
    default: 'false'
  node-version:
    description: 'Node.js version to use. If not provided, will use the version specified in the `.nvmrc` file.'
    required: false
    default: ''
  skip-allow-scripts:
    description: 'Skip the `yarn allow-scripts` step. If your job does not need this step, skipping it may save some time.'
    required: false
    default: 'false'
  yarn-install-max-retries:
    description: 'Maximum number of retries for the `yarn --immutable` install command.'
    required: false
    default: '5'
  yarn-custom-url:
    description: 'Optional custom URL for a Yarn bundle to be prepared and activated by Corepack'
    required: false
    default: ''
  use-yarn-hydrate:
    description: 'Use yarn hydration command instead of downloading yarn. When true, skips the custom yarn URL download.'
    required: false
    default: 'false'
  yarn-hydrate-command:
    description: 'Command to run for yarn hydration. Defaults to "yarn-binary:hydrate"'
    required: false
    default: 'npm run yarn-binary:hydrate' # Default command in Metamask extension

# The outputs are for the unit tests in `build-lint-test.yml`, and
# probably not useful for other workflows.
outputs:
  node-modules-cache-hit:
    description: 'Whether the node_modules cache was hit.'
    value: ${{ steps.download-node-modules.outputs.cache-hit || steps.try-skip-setup.outputs.cache-hit }}
  yarn-cache-hit:
    description: 'Whether the yarn cache was hit.'
    value: ${{ steps.restore-setup-node-cache.outputs.cache-hit }}
  node-version:
    description: 'The version of Node.js that was used.'
    value: ${{ steps.setup-node.outputs.node-version }}

runs:
  using: composite
  steps:
    # The "required: true" field is not enforced by GitHub, so we need to check
    # it manually.
    - name: Enforce required input is either "true" or "false"
      env:
        IS_HIGH_RISK_ENVIRONMENT: ${{ inputs.is-high-risk-environment }}
      run: |
        if [[ "$IS_HIGH_RISK_ENVIRONMENT" == "true" ]]; then
          echo 'High-risk environment detected. Disabling cache for security.'
        elif [[ "$IS_HIGH_RISK_ENVIRONMENT" == "false" ]]; then
          echo 'Low-risk environment detected. Enabling cache for optimized performance.'
        else
          echo "::error::Invalid value for 'is-high-risk-environment'. Must be 'true' (secure, no cache) or 'false' (faster, cache enabled)."
          exit 1
        fi
      shell: bash

    - name: Download .nvmrc from current commit (if it exists) to get node version
      if: ${{ inputs.node-version == '' }}
      id: download-nvmrc
      run: |
        wget -nv "https://raw.githubusercontent.com/${OWNER_AND_REPO}/${COMMIT_HASH}/.nvmrc"

        # If .nvmrc starts with "v" or starts with a number, take just the part before the second dot
        # "v24.13.0" becomes "v24.13"
        # "v24.13" stays as "v24.13"
        # "v24" stays as "v24"
        # "24.13.0" becomes "v24.13.0" and then "v24.13"
        # "lts/*" becomes the latest LTS version from `nvm ls-remote --lts`, for example "v24.13.0", and then "v24.13"
        if [[ -f .nvmrc ]]; then
          NVMRC_NODE_VERSION=$(tr -d '\r\n' < .nvmrc)

          # If it starts with a number but not "v", add "v" to the beginning. For example, "24.13.0" becomes "v24.13.0"
          if [[ "$NVMRC_NODE_VERSION" != v* && "$NVMRC_NODE_VERSION" =~ ^[0-9] ]]; then
            NVMRC_NODE_VERSION="v$NVMRC_NODE_VERSION"
          fi

          # If it's "lts/*", fetch "https://nodejs.org/download/release/index.json" and find the first version with "lts" not equal to false
          # (We cannot run `nvm ls-remote --lts` because nvm is not yet installed)
          if [[ "$NVMRC_NODE_VERSION" == "lts/*" ]]; then
            NVMRC_NODE_VERSION=$(curl -s https://nodejs.org/download/release/index.json | jq -r '[.[] | select(.lts != false)][0].version')
          fi

          # If NVMRC_NODE_VERSION is not empty, cut it to the major and minor version (e.g. "v24.13")
          NVMRC_NODE_VERSION=$(echo "$NVMRC_NODE_VERSION" | cut -d. -f1-2)

          # Now make sure it starts with "v" and is in the format "vX.Y" or "vX"
          if [[ "$NVMRC_NODE_VERSION" != v* || ! "$NVMRC_NODE_VERSION" =~ ^v[0-9]+(\.[0-9]+)?$ ]]; then
            echo "::error::Failed to determine Node.js version from .nvmrc. Please ensure .nvmrc exists and has a version number (with or without a 'v') or says "lts/*", or provide the node-version input directly."
            exit 1
          fi
        fi

        # If all this fails, fail the whole composite workflow
        if [[ -z "$NVMRC_NODE_VERSION" ]]; then
          echo "::error::Failed to determine Node.js version from .nvmrc. Please ensure .nvmrc exists and has a version number (with or without a 'v') or says "lts/*", or provide the node-version input directly."
          exit 1
        fi

        echo "nvmrc-node-version=$NVMRC_NODE_VERSION" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        OWNER_AND_REPO: ${{ github.repository }}
        COMMIT_HASH: ${{ inputs.ref || github.ref }}

    - name: Download yarn.lock from current commit in attempt to skip setup
      if: ${{ inputs.is-high-risk-environment == 'false' && inputs.cache-node-modules == 'true' && (inputs.node-version || steps.download-nvmrc.outputs.nvmrc-node-version) }}
      id: download-yarn-lock
      run: wget -nv "https://raw.githubusercontent.com/${OWNER_AND_REPO}/${COMMIT_HASH}/yarn.lock"
      shell: bash
      continue-on-error: true
      env:
        OWNER_AND_REPO: ${{ github.repository }}
        COMMIT_HASH: ${{ inputs.ref || github.ref }}

    - name: Try skipping setup if node-modules cache available
      if: ${{ inputs.is-high-risk-environment == 'false' && inputs.cache-node-modules == 'true' && steps.download-yarn-lock.outcome == 'success' && (inputs.node-version || steps.download-nvmrc.outputs.nvmrc-node-version) }}
      id: try-skip-setup
      uses: actions/cache/restore@v5
      with:
        path: '**/node_modules'
        key: node-modules-${{ runner.os }}-${{ runner.arch }}-${{ inputs.node-version || steps.download-nvmrc.outputs.nvmrc-node-version }}-${{ hashFiles('yarn.lock') }}
        lookup-only: true

    # Checkout repository only if not already checked out.
    - name: Checkout repository
      uses: actions/checkout@v6
      if: ${{ steps.try-skip-setup.outputs.cache-hit != 'true' && hashFiles('.git') == '' }}
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        ref: ${{ inputs.ref }}

    - run: corepack enable
      if: ${{ steps.try-skip-setup.outputs.cache-hit != 'true' }}
      shell: bash

    - name: Set up Node.js
      if: ${{ steps.try-skip-setup.outputs.cache-hit != 'true' }}
      uses: actions/setup-node@v6
      id: setup-node
      with:
        node-version: ${{ inputs.node-version || steps.download-nvmrc.outputs.nvmrc-node-version }}
        # node-version-file will be used if .nvmrc does not start with "v", for example "lts/*"
        node-version-file: ${{ (inputs.node-version == '' && steps.download-nvmrc.outputs.nvmrc-node-version == '') && '.nvmrc' || '' }}

    - name: Print Node.js version
      if: ${{ steps.try-skip-setup.outputs.cache-hit != 'true' }}
      run: |
        echo "Using Node.js version: ${{ steps.setup-node.outputs.node-version }}"
      shell: bash

    # Prepare and activate custom Yarn if URL is provided and hydration is not enabled.
    # This runs *before* setup-node might try to cache a standard Yarn.
    - name: Prepare and activate custom Yarn
      if: ${{ steps.try-skip-setup.outputs.cache-hit != 'true' && env.YARN_CUSTOM_URL && inputs.use-yarn-hydrate != 'true' }}
      env:
        COREPACK_ENABLE_UNSAFE_CUSTOM_URLS: 1
        YARN_CUSTOM_URL: ${{ inputs.yarn-custom-url }}
      run: |
        echo "Preparing and activating custom Yarn from URL: $YARN_CUSTOM_URL"
        corepack prepare "yarn@$YARN_CUSTOM_URL" --activate
      shell: bash

    # Hydrate yarn using the specified command when hydration is enabled
    - name: Hydrate Yarn
      if: ${{ steps.try-skip-setup.outputs.cache-hit != 'true' && inputs.use-yarn-hydrate == 'true' }}
      run: |
        echo "Hydrating Yarn using command: ${{ inputs.yarn-hydrate-command }}"
        ${{ inputs.yarn-hydrate-command }}
      shell: bash

    # In a low-risk environment, try to download cache of `node_modules`, if it
    # exists. On failure, will run the `yarn` command instead.
    - name: Download node_modules cache
      if: ${{ steps.try-skip-setup.outputs.cache-hit != 'true' && inputs.is-high-risk-environment == 'false' }}
      id: download-node-modules
      uses: actions/cache/restore@v5
      with:
        path: '**/node_modules'
        key: node-modules-${{ runner.os }}-${{ runner.arch }}-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('yarn.lock') }}

    - name: Conditionally restore action/setup-node cache
      if: ${{ steps.try-skip-setup.outputs.cache-hit != 'true' && inputs.is-high-risk-environment != 'true' && steps.download-node-modules.outputs.cache-hit != 'true' }}
      uses: actions/setup-node@v6
      id: restore-setup-node-cache
      with:
        node-version: ${{ steps.setup-node.outputs.node-version }}
        # If the `node_modules` cache was not found, use `setup-node` cache to
        # restore the `.yarn` folder.
        # Notes: if this is always set to 'yarn':
        #   1) Will not be secure for high-risk environment.
        #   2) Self-hosted runners will fail to find this cache, and then fail
        #      on the 'Post Setup environment' step
        #   3) This action will run a few seconds slower, because when we
        #      restore the `node_modules` folder from cache, there's no need to
        #      download the `.yarn` folder too
        cache: 'yarn'

    # If the node_modules cache was not found (or it's a high-risk environment),
    # run the yarn install
    - name: Install dependencies
      if: ${{ steps.try-skip-setup.outputs.cache-hit != 'true' && steps.download-node-modules.outputs.cache-hit != 'true'}}
      uses: MetaMask/action-retry-command@v1
      with:
        command: yarn --immutable
        shell: bash
        max-retries: ${{ inputs.yarn-install-max-retries }}

    # If the node_modules cache was found, run `yarn allow-scripts`. This is
    # typically run as part of the Yarn install, so we only need to run it if
    # we're restoring the cache.
    - name: Run `allow-scripts`
      if: ${{ steps.try-skip-setup.outputs.cache-hit != 'true' && inputs.skip-allow-scripts != 'true' && steps.download-node-modules.outputs.cache-hit == 'true'}}
      uses: MetaMask/action-retry-command@v1
      with:
        command: |
          if yarn bin allow-scripts &>/dev/null; then
            yarn allow-scripts
          fi
        shell: bash

    # Save the `node_modules` cache if it's not a high-risk environment and
    # caching is enabled.
    - name: Cache workspace
      if: ${{ steps.try-skip-setup.outputs.cache-hit != 'true' && inputs.is-high-risk-environment == 'false' && inputs.cache-node-modules == 'true' }}
      uses: actions/cache/save@v5
      with:
        path: '**/node_modules'
        key: node-modules-${{ runner.os }}-${{ runner.arch }}-${{ steps.download-nvmrc.outputs.nvmrc-node-version || steps.setup-node.outputs.node-version }}-${{ hashFiles('yarn.lock') }}
