name: Build, Lint, and Test

on:
  workflow_call:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout and setup environment
        id: checkout-and-setup
        uses: ./action.yml
        with:
          is-high-risk-environment: false
          cache-node-modules: true

  lint:
    name: Lint
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout and setup environment
        id: checkout-and-setup
        uses: ./action.yml
        with:
          is-high-risk-environment: false
          cache-node-modules: true
          node-version: ${{ matrix.node-version }}
      - run: yarn lint
      - name: Validate RC changelog
        if: ${{ startsWith(github.head_ref, 'release/') }}
        run: yarn lint:changelog --rc
      - name: Validate changelog
        if: ${{ !startsWith(github.head_ref, 'release/') }}
        run: yarn lint:changelog
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi
